# Generated by Django 4.2.8 on 2024-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0002_alter_certificate_teacher_alter_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name': 'TeacherInfo', 'verbose_name_plural': 'TeacherInfo'},
        ),
    ]
