# Generated by Django 5.0.7 on 2024-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0002_alter_faq_answer_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
