# Generated by Django 4.2.8 on 2024-07-23 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_alter_teacherinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
